# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72bdb6ca58177836e1ccd609ba7dbbddf3f62e950db1398eaad94fd99b073d21c0167aac21c942802af3731874a58e27f40348799561f054df6e8eedf4577d53

test:
  secret_key_base: 2cc1682a8819509b722c61986e8820e1db5852266f8fbea8d4f7c55332c297bd014aa16a297b807d0015579d132c3a0d247b3ddd7857219cce9729aea7efae1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
