# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9abbf2d299901c3144755078b88349ded1ade2c97341ded53a59617ade9bb5fc89b05af7779cba063c94f8b878f935941e0b09fc7302d31d065c1faf2f1bf5b5

test:
  secret_key_base: d96061e6473b1a912ce4332aac3974a85dcd67256cb669f287261c066c41f794ca6c5d64f36b20996298ca4a82f5ec8f1dc261f798d647b73af25f6860c7baf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
